import { pgTable, uuid, text, timestamp, boolean, jsonb } from 'drizzle-orm/pg-core'

export const responses = pgTable('responses', {
  id: uuid('id').primaryKey().defaultRandom(),
  submissionId: text('submission_id'),
  respondentId: text('respondent_id'),
  submittedAt: timestamp('submitted_at', { withTimezone: true }),
  firstName: text('first_name'),
  lastName: text('last_name'),
  email: text('email'),
  linkedinUrl: text('linkedin_url'),
  xUrl: text('x_url'),
  phoneNumber: text('phone_number'),
  countryOrigin: text('country_origin'),
  countryCurrent: text('country_current'),
  cityOrigin: text('city_origin'),
  cityCurrent: text('city_current'),
  discoveryChannel: text('discovery_channel'),
  discoveryDetail: text('discovery_detail'),
  referrerName: text('referrer_name'),
  partnerName: text('partner_name'),
  selfDescriptions: text('self_descriptions').array(),
  ideaInMind: text('idea_in_mind'),
  startupStages: text('startup_stages').array(),
  domainsOfInterest: text('domains_of_interest'),
  blockers: text('blockers'),
  startupTimelines: text('startup_timelines'),
  biggestChallenge: text('biggest_challenge'),
  startupField: text('startup_field'),
  supportNeeds: text('support_needs'),
  targetRoundUsd: text('target_round_usd'),
  valueAreas: text('value_areas'),
  ticketSizeUsd: text('ticket_size_usd'),
  preferredSectors: text('preferred_sectors').array(),
  investorStage: text('investor_stage'),
  whyJoin: text('why_join'),
  giveBack: text('give_back'),
  inviteeEmail: text('invitee_email'),
  rawPayload: jsonb('raw_payload'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  startupName: text('startup_name'),
  startupWebsite: text('startup_website'),
  approved: boolean('approved').default(false),
})

export type Response = typeof responses.$inferSelect
